pipeline {
    agent { label 'victorybeach.nl' }

    environment {
        GITHUB_REPO = "stolkie78/oracle"
        DESTINATION_DIR = "/home/debian/nginx"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }

        stage('Prepare Destination') {
            steps {
                echo 'Preparing destination directory...'
                sh '''
                if [ ! -d ${DESTINATION_DIR} ]; then
                    sudo mkdir -p ${DESTINATION_DIR}
                fi
                sudo rm -rf ${DESTINATION_DIR}/*
                '''
            }
        }

        stage('Copy Application') {
            steps {
                echo 'Copying application to destination...'
                sh '''
                sudo cp -r * ${DESTINATION_DIR}
                sudo chown -R www-data:www-data ${DESTINATION_DIR}
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}